name: Run Cosmos DB Emulator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      cosmos:
        image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
        ports:
          - 8081:8081
          - 10250-10255:10250-10255
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install certificate
        run: |
          retries=0
          max_retries=100
          until sudo curl -ksf "https://localhost:8081/_explorer/emulator.pem" -o '/usr/local/share/ca-certificates/cosmos.crt'; do
            echo "($retries/$max_retries) Downloading certificate failed, retrying in 1 second..."
            retries=$((retries+1))
            if [ $retries -ge $max_retries ]; then
              echo "Maximum retries reached. Exiting..."
              exit 1
            fi
            sleep 1
          done
          sudo update-ca-certificates

      - name: Run Example
        working-directory: ./src/Example
        run: dotnet run
          
